[project]
name = "conjugation-quiz"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "httpx>=0.28.1",
    "my-personal-spanish-conjugation-generator>=0.1.1",
    "pytest>=9.0.2",
]
